### ISSUE TITLE
Remove old version of limma hanging loose at bottom of the tool panel

### ISSUE THREAD

**Issue by mblue9** [usegalaxy-eu/usegalaxy-eu-tools#100]
Not sure if this is the place to put this, but just to let you know...

![screen shot 2018-06-14 at 12 51 49 pm](https://user-images.githubusercontent.com/5591821/41399401-938355c8-6ffd-11e8-8ad3-5a1416aad6d1.png)

**Comment by bgruening** [comment]
Ok, I think I fixed this. It will need a restart so I will leave this open for the moment, thanks for reporting.

**Comment by mblue9** [comment]
It's gone now, so closing.
