### ISSUE TITLE
There are 3 separate MultiQC tools in the current tool panel

### ISSUE THREAD

**Issue by mblue9** [usegalaxy-eu/usegalaxy-eu-tools#103]
I'm working through the ref-based RNA-seq tutorial and noticed there are 3 different MultiQC tools in the tool panel, see below (the top tool is v1.5.0, the 2nd is v1.0.0.0 and the 3rd is v1.3.1)

<img width="265" alt="screen shot 2018-07-01 at 11 23 40 am" src="https://user-images.githubusercontent.com/5591821/42137457-7dc8d7f4-7d21-11e8-8ccb-879fdcc0809b.png">

**Comment by bgruening** [comment]
It should be under quality control, right? I will fix this if you give me a green light.

**Comment by mblue9** [comment]
Yes 👍 
(in usegalaxy.org and in our instance the category where MultiQC is in the category "QC and Manipulation" but I see .eu has separate categories for those)

**Comment by bgruening** [comment]
Ok, try again in 10min :)

**Comment by mblue9** [comment]
👍 There's only one there now:
<img width="856" alt="screen shot 2018-07-01 at 12 48 15 pm" src="https://user-images.githubusercontent.com/5591821/42138116-1400c10e-7d2d-11e8-9f80-b1ceb77a373e.png">
