### ISSUE TITLE
There are 2 Trim Galore tools in tool panel

### ISSUE THREAD

**Issue by mblue9** [usegalaxy-eu/usegalaxy-eu-tools#104]
Similar to MultiQC (https://github.com/usegalaxy-eu/usegalaxy-eu-tools/issues/103) there are multiple Trim Galore tools, see screenshot, the top tool is v0.4.3.0 the 2nd is v0.4.3.1, keep just one tool under Quality Control?

<img width="277" alt="screen shot 2018-07-01 at 12 41 28 pm" src="https://user-images.githubusercontent.com/5591821/42138072-53a1ae1e-7d2c-11e8-9f35-62dc22cd2248.png">

**Comment by bgruening** [comment]
Is that nor more a manipulation tool than a QC tool?

**Comment by bgruening** [comment]
Fixed in 10min ...

**Comment by mblue9** [comment]
>Is that nor more a manipulation tool than a QC tool?

Maybe, and maybe that's a reason for the combined QC and manipulation category ;)

**Comment by bgruening** [comment]
;) I'm worried about even more tools in one category ... no?

**Comment by mblue9** [comment]
Yeah, maybe we should split up our single QC and manipulation category into 2 like yours. (Although just had a look your Quality Control category and it only has a few tools and some are quite old (SOLID!))

**Comment by bgruening** [comment]
Hiding SOLID?

**Comment by mblue9** [comment]
Yeah guess you could and then see if anyone complains 😄  Btw there are also tools like "Compute quality statistics" and "Draw nucleotides distribution chart" in your QC category that mention Solexa, not even Illumina ;)

**Comment by mblue9** [comment]
There's only 1 Trim Galore tool in the panel now so closing this.

**Comment by sneumann** [comment]
The second trim galore has resurfaced, could someone re-open the issue ? 

```
FASTA/FASTQ
Trim Galore! Quality and adapter trimmer of reads (0.4.3.1)
FASTQ Quality Control
Trim Galore! adaptive quality and adapter trimmer (0.4.0)
```
Or are they the same ?
```
Björn Grüning @bgruening 13:11:
yes, same tools. We need to merge both. 
```

**Comment by bgruening** [comment]
I can only guess that the underlying issue is this here: https://github.com/usegalaxy-eu/usegalaxy-eu-tools/pull/172

Let's hope it will not happen again.
I need to change local configs, but only if I have stable internet.

**Comment by bgruening** [comment]
Ok, I changed the shed_tool_conf as well ... hopefully this is fixed now once and for all :)
