### ISSUE TITLE
featureCounts built-in annotation not selectable

### ISSUE THREAD

**Issue by mblue9** [usegalaxy-eu/usegalaxy-eu-tools#107]
@bgruening the featureCounts built-in annotation is still problematic. I can't get it to show up with the current version in usegalaxy.eu, see screenshot below. The collection in the history has the dbkey mm10 so the dropdown for the built-in annotation should be visible but it's not:

<img width="1193" alt="screen shot 2018-07-06 at 3 04 39 pm" src="https://user-images.githubusercontent.com/5591821/42404091-7e3db824-81c9-11e8-8bc7-f3e813b95d03.png">

The built-in annotation does work in an older version of featureCounts in usegalaxy.eu (v1.6.0.2), see screenshot below (but it's not working/visible with any of the newer featureCounts versions 1.6.0.3, 1.6.0.5, 1.6.0.7, 1.6.1.0):

<img width="964" alt="screen shot 2018-07-07 at 9 40 46 am" src="https://user-images.githubusercontent.com/5591821/42404135-f5c99ab6-81c9-11e8-9444-771d2f14cbc7.png">

Would be great if this could be fixed as I need this annotation for tutorials and users.

**Comment by bgruening** [comment]
The build-ins are working now.

**Comment by mblue9** [comment]
Yep thanks 👍 How did you fix that? (in case it happens in our instance)

**Comment by bgruening** [comment]
I added it again to the gloabal tool_data_table_conf.xml file.
