### ISSUE TITLE
add info on using .lock files to ensure same versions across sites

### ISSUE THREAD

**Issue by frederikcoppens** [usegalaxy-eu/usegalaxy-eu-tools#114]
The overall idea is that one "reference" site (e.g. .eu) installs the .yaml file, which updates the .lock file by the CI service of that site. Next, all other usegalaxy.* sites install the .lock file. This procedure should be clarified in the documents.

**Comment by erasche** [comment]
Not quite right:

- we do not install first.
- we generate the lock files by checking the TS and then hard-coding the version into the yaml.lock files.
- then usegalaxy.eu (like everyone else) installs from the .lock file.

I've updated the readme.
