### ISSUE TITLE
Policies for adding new tools

### ISSUE THREAD

**Issue by frederikcoppens** [usegalaxy-eu/usegalaxy-eu-tools#116]
What tools do we add to any usegalaxy.* ? How to decide ? What are the requirements for tools ?
How can other communities go about adding tools ? make separate .yaml file ? 
Policies need to be made and advertised

**Comment by bgruening** [comment]
Criteria's to discuss:
* maintenance
  * it would be nice to know if this tool will be maintained for at least 1-2 years, by either an individual or better a group of people (galaxyp, iuc, genome-annotation)
* security
  * the security relevant guidelines from IUC should be fulfilled
* testing
  * tool should have tests, test-data and CI in the github repo
* accessbility
  * tools should be available on github/gitlab
* no special datatypes in the repo
* no tool_dependencies

**Comment by erasche** [comment]
We have identified polices as part of https://github.com/galaxyproject/usegalaxy-tools

They generally consist of:

- Additions to the minimum common tool set can be made by a pull request against this repository.
- Merging into the repo will be after approval by personnel at least 2 of the 3 sites.
  - Sites should check things like security, availability of tests, availability of the tool.
  - These specifics are not hard coded
- They will be published when we get closer to 18.05, when usegalaxy.*s can start to leverage that repository.
