### ISSUE TITLE
Adapt #CPUs for tool infernal cmbuild

### ISSUE THREAD

**Issue by mmiladi** [usegalaxy-eu/usegalaxy-eu-tools#118]
Hi,
infernal cmbuild (toolshed.g2.bx.psu.edu/repos/bgruening/infernal/infernal_cmbuild/1.1.2.0) computes a background model. Depending on the parameter `-L Total length of random sequences to search`, more palatalization is necessary, otherwise it would take hours to compute for usual cases.

The default -L value is 1.6 Megabases, which already need a few hours on single core. So 10-20 cores would be suggested for -L 1.6. For lower -L values however we can reduce the number of cores to 4-10. 

The run time is expected to be linear to the -L value.

**Comment by erasche** [comment]
Hi @mmiladi, sorry I did not respond to this. We currently can do this but it is complex and requires writing custom code. We do not have a good model for this, but it gets better now that we can collect cgroups information. We still look to write something generic, and not specific to individual tools.
