### ISSUE TITLE
tool_conf.xml sample file 

### ISSUE THREAD

**Issue by ieguinoa** [usegalaxy-eu/usegalaxy-eu-tools#129]
Hi,

I was wondering if it's possible to get the tool_conf.xml file behind usegalaxy.eu including the labels and sections with ids.
I'm asking because I'm trying to create one using all the sections in tools_iuc/europe_custom yaml.lock and including all the labels from usegalaxy.eu but I found some sections are duplicated (e.g FASTA/FASTQ manipulation) and with different sections in them. If I try to install tools using for example the tools_iuc yaml file it won't have the expected results in the installation, are these the files used or do you have other yaml files based on section ids? 

Thanks in advance!
Ignacio

**Comment by bgruening** [comment]
You can find it here: https://gist.github.com/bgruening/1137798bef20144262659ac96c78bc29
There are multiple tools hidden and deprecated that you probably don't want.

**Comment by erasche** [comment]
We only base our tool installation off of section name. We need to clean it up but have not found the time yet.

**Comment by erasche** [comment]
Live version of tool conf is now available here: https://github.com/usegalaxy-eu/infrastructure-playbook/tree/master/files/galaxy/config

We have done a major re-organisation together with the other usegalaxy.* servers to clean up our toolboxes
