### ISSUE TITLE
SnpEff tools version-ordering is a mess

### ISSUE THREAD

**Issue by wm75** [usegalaxy-eu/usegalaxy-eu-tools#150]
https://toolshed.g2.bx.psu.edu/repository?repository_id=93a5efea7e957b53&changeset_revision=36dc3690a82c lists the following current versions of the SnpEff tools:

- SnpEff build: 4.3+T.galaxy3
- SnpEff chromosome-info: 4.3+T.galaxy1
- SnpEff download: 4.3+T.galaxy2
- SnpEff eff: 4.3+T.galaxy1
- SnpEff databases: 4.3+T.galaxy1

of these, we have installed all but the latest SnpEff build version (we only have 4.3+T.galaxy2 for it), but for SnpEff download, eff, and databases the latest version is not recognized as such, which makes it very hard for users to find out what they are supposed to use. For SnpEff chromosome-info, the latest version is recognized as it should be, but there is an unfortunate `@wrapper_version@.galaxy1` version offered in the list, with an accidentally lower-cased version token.

Suggestions:
- SnpEff chromosome-info: hide or remove `@wrapper_version@.galaxy1` version
- SnpEff build: install `4.3+T.galaxy3` and hide the older version
- SnpEff download, eff and databases: hide all subversions from the 4.3 series except the latest one

**Comment by wm75** [comment]
@bgruening Much better now, thanks!

(Only remaining issue, but probably it can't be solved with these unfortunate version names: when you rerun a job involving one of these tools, you're still getting a friendly, but wrong reminder from Galaxy that you are not using the latest version.)

**Comment by bgruening** [comment]
We could remove the old versions all together ...

**Comment by wm75** [comment]
Probably not worth it. Maybe it's better to just wait for a new release with a proper version?

**Comment by bgruening** [comment]
Like that!
