### ISSUE TITLE
2 x Merge columns tool in tool panel

### ISSUE THREAD

**Issue by mblue9** [usegalaxy-eu/usegalaxy-eu-tools#179]
There seems to be 2 of the Merge columns tool in the panel

![Screen Shot 2019-05-04 at 5 03 23 PM](https://user-images.githubusercontent.com/5591821/57175403-fb2db980-6e8e-11e9-942a-7c11f10f4c09.png)

**Comment by bgruening** [comment]
Fixed! Thanks for reporting!
