### ISSUE TITLE
Updating Galaxy-E tool panel content

### ISSUE THREAD

**Issue by yvanlebras** [usegalaxy-eu/usegalaxy-eu-tools#225]
Hi wonder usegalaxy.eu ,

I think the actual tool panel from ecology.usegalaxy.eu is not using https://github.com/usegalaxy-eu/usegalaxy-eu-tools/blob/master/ecology.yaml tools list and maybe I was wrong thinking that this .yaml was directly connected to the tools list on the tool panel ? So this PR to initiate the update of the tool panel ;)

Whishing you a good day!

**Comment by bgruening** [comment]
> So this PR to initiate the update of the tool panel ;)

This is not a PR, I'm confused :)
Indeed the filtering is handles by these functions: https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/templates/galaxy/config/global_host_filters.py.j2

We had plans to make these functions consume the yaml files and create the filtered boxes, but we haven't found time for it :(

**Comment by yvanlebras** [comment]
ouch, I'm too bad in gh... :( next time will be better I hope ;)

ok, if can help somewhere or do something to update the tool list, don't hesitate to point me. If the need is time, don't worry it's not urgent ;)

**Comment by yvanlebras** [comment]
Maybe "just" making a PR (a rela one ;) ) to https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/templates/galaxy/config/global_host_filters.py.j2 ;)

**Comment by yvanlebras** [comment]
hmmm, looking at the file it seems that maybe I can make some errors :
- is there a difference between these sections: "display_data" vs "graph_diplay_data" ?
- RAD-seq tool section is named "rad-seq" ?

**Comment by yvanlebras** [comment]
Ooops, I did it again ;)

https://github.com/usegalaxy-eu/infrastructure-playbook/pull/106

**Comment by bgruening** [comment]
@yvanlebras is this still valid?

**Comment by yvanlebras** [comment]
No, all is perfect now ! Thanks!
