### ISSUE TITLE
OpenLayers map visualization failed due to "load function 'load' not found"

### ISSUE THREAD

**Issue by yvanlebras** [usegalaxy-eu/usegalaxy-eu-tools#242]
Hi eu,

Trying to visualize geolocalized datasets, I have this error launching the OpenLayers map visualization"load function 'load' not found".

Best,

Yvan

**Comment by yvanlebras** [comment]
You can look at this history to test from a shapefile or a GeoJSON datasets (step 12 or 13) https://ecology.usegalaxy.eu/u/ylebras/h/loligo-vulgaris-ebv-workflow-test-from-gbif

**Comment by annefou** [comment]
I have the same problem too!

**Comment by yvanlebras** [comment]
Hi @annefou It seems that the issue is fixed for me. Can you try to validate it ? Cheers, Yvan

**Comment by bgruening** [comment]
Oh yeah, I fixed that! Sorry, I forgot to close it.

**Comment by yvanlebras** [comment]
thank YOU SO MUCH!!
