### ISSUE TITLE
handlers restart

### ISSUE THREAD

**Issue by kpoterlowicz** [usegalaxy-eu/usegalaxy-eu-tools#282]
Hi @bgruening, would it be possible to restart handlers as https://github.com/usegalaxy-eu/usegalaxy-eu-tools/pull/279 is not updated in usegalaxy.eu ?

**Comment by bgruening** [comment]
@kpoterlowicz the tool was stuck in the cloning state. I fixed that now. Can you please check again?

**Comment by bgruening** [comment]
Should the multiple tools be deinstalled?

Am 04.03.20 um 21:04 schrieb Krzysztof Poterlowicz:

**Comment by kpoterlowicz** [comment]
Yes they should
K

**Comment by bgruening** [comment]
done.

Am 04.03.20 um 21:16 schrieb Krzysztof Poterlowicz:
> Yes they should
> K
>
