### ISSUE TITLE
Tool request: footprint

### ISSUE THREAD

**Issue by MzwaneleN** [usegalaxy-eu/usegalaxy-eu-tools#309]
I would like to request a tool : https://toolshed.g2.bx.psu.edu/repos/rnateam/footprint

**Comment by bgruening** [comment]
@MzwaneleN I added it in https://github.com/usegalaxy-eu/usegalaxy-eu-tools/commit/688159069bec20280116292fcfbc9d675e420b5e it gets installed next Saturday.

Thanks!

**Comment by MzwaneleN** [comment]
Thanks
