### ISSUE TITLE
Hide all versions of SAM-BAM and BAM-SAM

### ISSUE THREAD

**Issue by wm75** [usegalaxy-eu/usegalaxy-eu-tools#321]
These tools:
- `toolshed.g2.bx.psu.edu/repos/devteam/sam_to_bam/sam_to_bam`
- `toolshed.g2.bx.psu.edu/repos/devteam/sam_to_bam/bam_to_sam`

are very outdated and completely superseded by `samtools view`.
The shed_tool_conf.xml list them in the `sam_bam` section, but there seem to be older versions still in `sam_bam_manipulation`.
All of them are safe to hide, I'd say.

**Comment by bgruening** [comment]
All of them should be hidden. Thanks. 
Please note that if there should be any TS updates to those tools they will probably be reinstalled. The only solution I can offer for not is __moving__ those tools to the europe-custom.yaml + yaml.lock or any other yaml file that is not autoinstalled.
