### ISSUE TITLE
MITOS missing in the tool panel

### ISSUE THREAD

**Issue by bernt-matthias** [usegalaxy-eu/usegalaxy-eu-tools#328]
Dear usegalaxy-eu team. 

MITOS and MITOS2 are installed but MITOS is not in the tool panel and can also not be found in the search. 

https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Fmitos%2Fmitos
https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Fmitos2%2Fmitos2

Is there the possibility to have a certain order for the MITOS2 reference data? I would like to have a certain default.

**Comment by bgruening** [comment]
Should be installed now.
