### ISSUE TITLE
Including the CHROMEISTER tool in usegalaxy-eu-tools

### ISSUE THREAD

**Issue by estebanpw** [usegalaxy-eu/usegalaxy-eu-tools#336]
We recently merged the CHROMEISTER tool in the IUC tools repository (see merged PR [here](https://github.com/galaxyproject/tools-iuc/pull/3220)). Is it possible to include it in the usegalaxy-eu-tools repository so that it is available in [https://usegalaxy.eu/](https://usegalaxy.eu/)?

If yes, I will submit a PR. Thanks a lot!

**Comment by bgruening** [comment]
I already did this :) 
https://github.com/usegalaxy-eu/usegalaxy-eu-tools/commit/a7a8ee3bb7c8f9517a2f9558b7c46e82061db8e7

It will be installed tomorrow automatically.
Please also see https://github.com/estebanpw/chromeister/pull/11
