### ISSUE TITLE
Update on kraken2tax 

### ISSUE THREAD

**Issue by macelik** [usegalaxy-eu/usegalaxy-eu-tools#359]
Dear Admins,

There is no available DB (taxonomy database) on the tool called kraken2tax (https://toolshed.g2.bx.psu.edu/repos/devteam/kraken2tax) while i can use it on usegalaxy.org. Could you please check it?

Thank you

**Comment by bgruening** [comment]
Hi @macelik 

this should now been fixed.

Ciao,
Bjoern
