### ISSUE TITLE
new tool needed

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/usegalaxy-eu-tools#52]
* given two files ...
* in both files is a column with integers/float
* merge/join both files so that the one float of one file is most similar to a float of the other file

**Comment by erasche** [comment]
maybe cross reference this to galaxy-freiburg and tag `hiwi-project`?

**Comment by bgruening** [comment]
👍

**Comment by bgruening** [comment]
Done with https://github.com/bgruening/galaxytools/tree/master/tools/text_processing/join_files_on_column_fuzzy
