### ISSUE TITLE
data_manager_build_amrfinderplus is not an existing toolshed tool

### ISSUE THREAD

**Issue by wm75** [usegalaxy-eu/usegalaxy-eu-tools#542]
@bgruening you added this DM in https://github.com/usegalaxy-eu/usegalaxy-eu-tools/commit/2079259bd223e036879d8521d7edaa7c64d9a46f, but the DM's merge commit https://github.com/galaxyproject/tools-iuc/commit/59077a173599fc9d355a5d36ad7875050dbe3e19 didn't trigger any deployment.
Now adding new tools to tools_iuc.yaml causes linting problems.

**Comment by bgruening** [comment]
But its here https://toolshed.g2.bx.psu.edu/view/iuc/amrfinderplus_data_manager_build/eea0c38a9afd

**Comment by bgruening** [comment]
I see ...

**Comment by bgruening** [comment]
Its called [amrfinderplus_data_manager_build](https://toolshed.g2.bx.psu.edu/repository/browse_repository?id=ab3771d6cb572781)
