### ISSUE TITLE
Update metabolomics tools to latest versions

### ISSUE THREAD

**Issue by hechth** [usegalaxy-eu/usegalaxy-eu-tools#596]
Would be great to have the `Metabolomics` section up-to-date and to also add new tools which have become available in the meantime. @yguitton or @melpetera is someone able to pick this up?

**Comment by bgruening** [comment]
It this one done @hechth ?

**Comment by hechth** [comment]
Unfortunately not

**Comment by bgruening** [comment]
@hechth do you want to work on this? Just update all tools to the latest version.
