### ISSUE TITLE
"Could not find tool" error appears occasionally

### ISSUE THREAD

**Issue by kostrykin** [usegalaxy-eu/usegalaxy-eu-tools#598]
Yesterday I added a new tool to the imaging section, see #597 2bee8e67b71573dc31a7a6a580beb97b4895343a.

When opening the tool on usegalaxy.eu, or using [the link of the tool](https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/imgteam/superdsm/ip_superdsm/0.1.2-1), about half of the time the error 

> Loading tool toolshed.g2.bx.psu.edu/repos/imgteam/superdsm/ip_superdsm/0.1.2-1 failed: Could not find tool with id 'toolshed.g2.bx.psu.edu/repos/imgteam/superdsm/ip_superdsm/0.1.2-1'.

appears, but the tool is loaded the other half of the time. The same also can holds for the tool appearing in the list of tools (sometimes it appears in the list, sometimes it does not).

Screenshots are provided below.

---

<img width="1014" alt="Bildschirmfoto 2023-06-26 um 17 59 16" src="https://github.com/usegalaxy-eu/usegalaxy-eu-tools/assets/6557139/d97477e0-8245-4d50-9e6c-d0f0af177b0b">

---

<img width="1016" alt="Bildschirmfoto 2023-06-26 um 17 59 40" src="https://github.com/usegalaxy-eu/usegalaxy-eu-tools/assets/6557139/87e1a789-d47b-4e50-a15b-6e3d14fc99f0">

**Comment by bgruening** [comment]
One web handler was out of sync. Please try again.

**Comment by kostrykin** [comment]
thanks for the quick fix!
