### ISSUE TITLE
Add pairtools

### ISSUE THREAD

**Issue by diegomics** [usegalaxy-eu/usegalaxy-eu-tools#605]
This is the tool recommended by Dovetail™ Omni-C™ for alignment processing (similar to Picard). It's much simpler to use.
The idea is to use it for ERGA workflows that are in the making ;)

Links:
https://anaconda.org/bioconda/pairtools
https://pairtools.readthedocs.io/en/latest/
https://omni-c.readthedocs.io/en/latest/

I'm tagging @gallardoalba here since we talked about it :)

**Comment by gallardoalba** [comment]
Thanks @diegomics, I'll continue working in the ERGA project today. Regards

**Comment by SaimMomin12** [comment]
Closing the issue as `pairtools` was added to Galaxy :)
