### ISSUE TITLE
Prevent adding a tool to a new panel if already present

### ISSUE THREAD

**Issue by lldelisle** [usegalaxy-eu/usegalaxy-eu-tools#649]
I think it would be good that when a new tool is added, the CI checks that the tool is not already present into another yaml.

**Comment by bgruening** [comment]
We actually want to go the other direction and allow this explicity, so that every community can maintain and assemble their own toolset.

**Comment by lldelisle** [comment]
But what is the link between the tool panel and the community? The tool panel is used for subdomains?
