### ISSUE TITLE
Please add barrnap

### ISSUE THREAD

**Issue by youyuh48** [usegalaxy-eu/usegalaxy-eu-tools#715]
Thank you for maintaining your wonderful Galaxy.
Could you please install the barrnap tool at the following URL?

https://toolshed.g2.bx.psu.edu/repository?repository_id=52fc6d4b544460ef

Best regards

**Comment by bgruening** [comment]
Hi @youyuh48, thanks for reaching out. The tool should be available under https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/barrnap/barrnap/1.2.2

**Comment by youyuh48** [comment]
Hi @bgruening Thanks!
